language: node_js
node_js: 12
addons:
    artifacts:
        paths:
            - __tests__/__image_snapshots__/__diff_output__/
            - storybook-static/
            - failed-storyshots.html
install:
  - npm install
script:
  - npm test
  - npm run lint
