language: node_js
node_js: 12
addons:
  artifacts:
    paths:
      - __tests__/__image_snapshots__/__diff_output__/
      - storybook-static/
      - failed-storyshots.html
install:
  - npm install
script:
  - npm test
  - npm run lint
deploy:
    - skip_cleanup: true
      provider: npm
      email: jenkins@xenit.eu
      api_key: $NPM_TOKEN
      on:
        tags: true
        condition: "$TRAVIS_TAG != v*.*.*-*" # Not for versions of the form x.x.x-prerelease
        repo: xenit-eu/finder-ui
    - skip_cleanup: true
      provider: npm
      tag: next
      email: jenkins@xenit.eu
      api_key: $NPM_TOKEN
      on:
        tags: true
        condition: "$TRAVIS_TAG == v*.*.*-*" # For versions of the form x.x.x-prerelease
        repo: xenit-eu/finder-ui
   - skip_cleanup: true
     provider: pages
     github_token: $GITHUB_TOKEN
     local_dir: ./storybook-static/
     keep_history: true
     committer_from_gh: true
     on:
         branch: master
